name: CI/CD - DeliveryOps Homologação

on:
  push:
    branches: [ "main" ]

jobs:
  publish:
    runs-on: ubuntu-latest

    #permissions:
    #  contents: 'read'
    #  id-token: 'write'
    env:
      IMAGE_NAME: gcr.io/mottu-321312/hello-mottu

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      #- name: Login To GCP
      #  uses: google-github-actions/setup-gcloud@v1.1.1
      #  with:
      #    project_id: "mottu-321312"
      #    service_account_email: "teste-github@mottu-321312.iam.gserviceaccount.com"
      #    service_account_key: ${{ secrets.GCP_CREDENTIALS }}
      - name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v1'
        with:
          token_format: 'access_token'
          credentials_json: '${{ secrets.GOOGLE_CREDENTIALS }}'

    # This example uses the docker login action
      - uses: 'docker/login-action@v1'
        with:
          registry: 'gcr.io' # or REGION-docker.pkg.dev
          username: 'oauth2accesstoken'
          password: '${{ steps.auth.outputs.access_token }}'

    # This example runs "docker login" directly to Artifact Registry.
    #- run: |-
     #   echo '${{ steps.auth.outputs.access_token }}' | docker login -u oauth2accesstoken --password-stdin https://REGION-docker.pkg.dev

    # This example runs "docker login" directly to Container Registry.
      - run: |-
          echo '${{ steps.auth.outputs.access_token }}' | docker login -u oauth2accesstoken --password-stdin https://gcr.io

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v1

      - name: Use gcloud CLI
        run: gcloud info

      - name: Configure Docker
        run: gcloud auth configure-docker --quiet

      - name: Build Docker image
        run: docker build . -t $IMAGE_NAME:$GITHUB_RUN_ID

      - name: Push Docker image
        run: docker push $IMAGE_NAME:$GITHUB_RUN_ID
