name: CI/CD - DeliveryOps Homologação

on:
  push:
    branches: [ "main" ]

jobs:
  publish:
    runs-on: ubuntu-latest

    #permissions:
    #  contents: 'read'
    #  id-token: 'write'
    env:
      IMAGE_NAME: gcr.io/mottu-321312/hello-mottu

    steps:
      - name: Login To GCP
        uses: google-github-actions/setup-gcloud@v1.1.1
        with:
          #project_id: "mottu-321312"
          #service_account_email: "teste-github@mottu-321312.iam.gserviceaccount.com"
          service_account_key: ${{ secrets.GCP_CREDENTIALS }}

      - name: Configure Docker
        run: gcloud auth configure-docker --quiet

      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Build Docker image
        run: docker build . -t $IMAGE_NAME:$GITHUB_RUN_ID

      - name: Push Docker image
        run: docker push $IMAGE_NAME:$GITHUB_RUN_ID
