name: CI/CD - DeliveryOps Homologação

on:
  push:
    branches: [ "main" ]

jobs:
  publish:
    runs-on: ubuntu-latest

    #permissions:
    #  contents: 'read'
    #  id-token: 'write'
    env:
      IMAGE_NAME: gcr.io/mottu-321312/hello-mottu

    steps:
    - uses: 'actions/checkout@v3'

    - id: 'auth'
      name: 'Authenticate to Google Cloud'
      uses: 'google-github-actions/auth@v1'
      with:
        credentials_json: '${{ secrets.GCP_CREDENTIALS }}'

    - name: Use gcloud CLI
      run: gcloud info

    - name: Configure Docker
      run: gcloud auth configure-docker --quiet

    - name: Build Docker image
      run: docker build . -t $IMAGE_NAME:$GITHUB_RUN_ID

    - name: Push Docker image
      run: docker push $IMAGE_NAME:$GITHUB_RUN_ID
